{'id': 'eb5407b00f144cdaa614c51d5cb50233',
 'data': {'command': ['open',
                      '/Applications/Adobe Premiere Pro 2021/Adobe Premiere Pro 2021.app'],
          'options': {
              'env': {
                  'TMPDIR': '/var/folders/2t/rwz1qjd505q4p0k81rr3lfjm0000gn/T/',
                  'XPC_FLAGS': '0x0',
                  'TERM_PROGRAM_VERSION': '433',
                  'TERM_PROGRAM': 'Apple_Terminal',
                  'XPC_SERVICE_NAME': '0',
                  'TERM_SESSION_ID': '303A986D-8644-413B-A4FC-C1685A082664',
                  'TERM': 'xterm-256color',
                  'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.k3c2mPjuSJ/Listeners',
                  'SHELL': '/bin/zsh',
                  'HOME': '/Users/andyguo',
                  'LOGNAME': 'wuqingjun@qiyi.com',
                  'USER': 'andyguo',
                  'PATH': '/Users/andyguo/miniconda3/envs/conda_py/bin:/Users/andyguo/miniconda3/condabin:/Users/andyguo/bin:/usr/local/bin:/usr/local/USD/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/opt/rez/bin/rez',
                  'SHLVL': '1',
                  'PWD': '/Applications',
                  'OLDPWD': '/Users/andyguo/Documents/GitHub/fastapi_demo/app/plugins/hello',
                  'PYTHONPATH': '/Applications/ftrack Connect.app/Contents/Resources/resource/connect-standard-plugins/ftrack-application-launcher-1.0.1/dependencies:/usr/local/USD/lib/python:',
                  'ZSH': '/Users/andyguo/.oh-my-zsh',
                  'PAGER': 'less',
                  'LESS': '-R',
                  'LSCOLORS': 'Gxfxcxdxbxegedabagacad',
                  'AUTOJUMP_SOURCED': '1',
                  'AUTOJUMP_ERROR_PATH': '/Users/andyguo/Library/autojump/errors.log',
                  'JAVA_HOME': '/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home',
                  'CONDA_EXE': '/Users/andyguo/miniconda3/bin/conda',
                  '_CE_M': '',
                  '_CE_CONDA': '',
                  'CONDA_PYTHON_EXE': '/Users/andyguo/miniconda3/bin/python',
                  'CONDA_SHLVL': '2',
                  'CONDA_PREFIX': '/Users/andyguo/miniconda3/envs/conda_py',
                  'CONDA_DEFAULT_ENV': 'conda_py',
                  'CONDA_PROMPT_MODIFIER': '(conda_py) ',
                  'CONDA_PREFIX_1': '/Users/andyguo/miniconda3',
                  'LC_CTYPE': 'UTF-8',
                  '_': '/Applications/ftrack Connect.app/Contents/MacOS/ftrack_connect',
                  '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0',
                  'REQUESTS_CA_BUNDLE': '/Applications/ftrack Connect.app/Contents/Resources/resource/cacert.pem',
                  'WEBSOCKET_CLIENT_CA_BUNDLE': '/Applications/ftrack Connect.app/Contents/Resources/resource/cacert.pem',
                  'SSL_CERT_FILE': '/Applications/ftrack Connect.app/Contents/Resources/resource/cacert.pem',
                  'FTRACK_CONNECT_PLUGIN_PATH': '/Applications/ftrack Connect.app/Contents/Resources/resource/connect-standard-plugins',
                  'FTRACK_CONNECT_PACKAGE_RESOURCE_PATH': '/Applications/ftrack Connect.app/Contents/Resources/resource',
                  'QT_PREFERRED_BINDING': 'PySide2',
                  'FTRACK_SERVER': 'https://iqiyi.ftrackapp.cn',
                  'FTRACK_API_USER': 'wuqingjun@qiyi.com',
                  'FTRACK_API_KEY': 'YWRkOGViNTgtZDJlZi00ODVjLWJhMDYtNjhiZmQyNWI4ZTFjOjplMGNjZTEzNy04MDg1LTRmNmUtOGVjOC1kN2IyZDhkZjkxMjA',
                  'FTRACK_APPLICATION_LAUNCHER_CONFIG_PATHS': '/Applications/ftrack Connect.app/Contents/Resources/resource/connect-standard-plugins/ftrack-application-launcher-1.0.1/config',
                  'FTRACK_EVENT_SERVER': 'https://iqiyi.ftrackapp.cn',
                  'FTRACK_APIKEY': 'YWRkOGViNTgtZDJlZi00ODVjLWJhMDYtNjhiZmQyNWI4ZTFjOjplMGNjZTEzNy04MDg1LTRmNmUtOGVjOC1kN2IyZDhkZjkxMjA',
                  'FTRACK_CONNECT_EVENT': 'eyJhY3Rpb25JZGVudGlmaWVyIjogImZ0cmFjay1jb25uZWN0LWxhdW5jaC1hZG9iZSIsICJsYWJlbCI6ICJQcmVtaWVyZSBQcm8iLCAidmFyaWFudCI6ICJDQyAyMDIxIiwgImRlc2NyaXB0aW9uIjogbnVsbCwgImljb24iOiAiaHR0cHM6Ly9pcWl5aS5mdHJhY2thcHAuY24vYXBwbGljYXRpb25faWNvbnMvcHJlbWllcmUucG5nIiwgImFwcGxpY2F0aW9uSWRlbnRpZmllciI6ICJwcmVtaWVyZV9wcm9fQ0MgMjAyMSIsICJob3N0IjogIkFuZHktSVFJWUkubG9jYWwiLCAic2VsZWN0aW9uIjogW10sICJzb3VyY2UiOiB7ImlkIjogIjVhZDcxYTU1ZGVmZTQ2MGFiYjdkODAwNDFlOWFkNDc1IiwgInVzZXIiOiB7InVzZXJuYW1lIjogInd1cWluZ2p1bkBxaXlpLmNvbSJ9fX0='},
              'close_fds': True,
              'cwd': '/Applications/Adobe Premiere Pro 2021',
              'preexec_fn': '< built - in function setsid >'},
          'application': {'identifier': 'premiere_pro_CC 2021',
                          'path': '/Applications/Adobe Premiere Pro 2021/Adobe Premiere Pro 2021.app',
                          'launchArguments': None,
                          'version': LooseVersion('2021'),
                          'label': 'Premiere Pro',
                          'icon': 'https://iqiyi.ftrackapp.cn/application_icons/premiere.png',
                          'variant': 'CC 2021',
                          'description': None,
                          'integrations': {}},
          'context': {'actionIdentifier': 'ftrack-connect-launch-adobe',
                      'label': 'Premiere Pro',
                      'variant': 'CC 2021',
                      'description': None,
                      'icon': 'https://iqiyi.ftrackapp.cn/application_icons/premiere.png',
                      'applicationIdentifier': 'premiere_pro_CC 2021',
                      'host': 'Andy-IQIYI.local',
                      'selection': [],
                      'source': {'id': '5ad71a55defe460abb7d80041e9ad475',
                                 'user': {'username': 'wuqingjun@qiyi.com'}}},
          'integration': {'name': None,
                          'version': None,
                          'env': {},
                          'launch_arguments': []}},
 'topic': 'ftrack.connect.application.launch',
 'sent': None,
 'source': {
     'id': '5ad71a55defe460abb7d80041e9ad475',
     'user': {'username': 'wuqingjun@qiyi.com'}},
 'target': '',
 'in_reply_to_event': None}
