{'id': 'c8d5cc8feb5146dab7992fd5a0be08a3',
 'data': {'query': '',
          'groupers': [],
          'filters': [{'disabled': True,
                       'property': 'name',
                       'initialConfig': {'disabled': True,
                                         'property': 'name',
                                         'root': 'data',
                                         'id': 'combobox-2000544-query-filter'},
                       'root': 'data',
                       'id': 'combobox-2000544-query-filter'}],
          'sorters': []},
 'topic': 'ftrack.storage-scenario.discover',
 'sent': None,
 'source': {'id': 'db9800e0824e48b4855a26108de68276',
            'user': {'username': 'wuqingjun@qiyi.com',
                     'id': 'bcdf57b0-acc6-11e1-a554-f23c91df1211'}},
 'target': '',
 'in_reply_to_event': None}
